apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9091
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'Loki'
        tags: ['container','compose_service']
      tracesToMetrics:
        datasourceUid: 'Prometheus'
      serviceMap:
        datasourceUid: 'Prometheus'