db:
  dsn: "postgres://user:password@db-host:5432/pingerus?sslmode=disable"
  max_conns: 10
  min_conns: 1
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m
  health_check_period: 1m
  query_timeout: 5s

kafka_in:
  brokers: ["kafka:9092"]
  topic: "status-change"
  group_id: "email-notifier"

smtp:
  addr: "mailhog:1025"
  from: "noreply@pingerus.com"
  user: "apikey"
  password: "smtp-password"
  use_tls: false
  timeout: 10s
  subj_prefix: "[Pingerus]"

server:
  metrics_addr: ":8084"

log_level: "debug"
