db:
  dsn: "postgres://user:password@db-host:5432/pingerus?sslmode=disable"
  max_conns: 10
  min_conns: 1
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m
  health_check_period: 1m
  query_timeout: 5s

kafka:
  brokers: ["kafka:9092"]
  topic: "check-request"

sched:
  tick: 30s
  batch_limit: 100
  metrics_addr: ":8082"

otel:
  enable: true
  otlp_endpoint: "otel-collector:4317"
  service_name: "scheduler"
  sample_ratio: 0.1

log_level: "debug"
